/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.progettoinfo;

/**
 *
 * @author tonma
 */
public class FormArmateDelMale extends javax.swing.JFrame {
    
    private int numeroArmateTotali = 10;
    private int numeroEroiTotali = 2;
    private int numeroEsperienza = 1;
    private int forzaTotale;
    private String [] nomiEroi = {"Trump","HIV","Peste"};
    MainForm form;

    /**
     * Creates new form FormArmateDelMale
     */
    public FormArmateDelMale(int forzaTotale, MainForm form) {
        initComponents();
        this.forzaTotale = forzaTotale;
        this.form = form;
    }
    
    
    public int calcolaForza (int inf, int cov, int eb, int ang, int numEroi){
        Influenza i = new Influenza (numeroEsperienza);
        Covid c = new Covid (numeroEsperienza);
        Ebola e = new Ebola (numeroEsperienza);
        AngelaDaMondello a = new AngelaDaMondello (numeroEsperienza);
        Eroe [] eroi = new Eroe [numEroi];
        int forzaEroi = 0;
        for(Eroe er : eroi){
            er = new Eroe(numeroEsperienza, nomiEroi[(int)(Math.random()*3)], (int)(Math.random()*11+1), "male");
            forzaEroi += e.getForza();
        }
        int forza = i.getForza()*inf + c.getForza()*cov+e.getForza()*eb+a.getForza()*ang+forzaEroi;
        return forza;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numeroInfluenze = new javax.swing.JTextField();
        numeroCovid = new javax.swing.JTextField();
        numeroEbola = new javax.swing.JTextField();
        numeroAngele = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        esperienza = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        armateTotali = new javax.swing.JLabel();
        eroiTotali = new javax.swing.JLabel();
        compraEsperienza = new javax.swing.JButton();
        vendiButton = new javax.swing.JButton();
        consegnaButton = new javax.swing.JButton();
        errore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Inserire il numero di influenze");

        jLabel2.setText("Inserire il numero di Covid");

        jLabel3.setText("Inserisci il numero di Ebola");

        jLabel4.setText("Inserisci il numero di Angela Da Mondello");

        jLabel5.setText("Le tue armate hanno un'esperienza di: ");

        esperienza.setText("1");

        jLabel7.setText("/10");

        jLabel8.setText("Armate totali disponibili");

        jLabel9.setText("Numero di eroi");

        armateTotali.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        armateTotali.setText("10");

        eroiTotali.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        eroiTotali.setText("2");

        compraEsperienza.setText("Compra esperienza");
        compraEsperienza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraEsperienzaActionPerformed(evt);
            }
        });

        vendiButton.setText("Vendi esperienza");
        vendiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendiButtonActionPerformed(evt);
            }
        });

        consegnaButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        consegnaButton.setText("Consegna Formazione");
        consegnaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consegnaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(compraEsperienza)
                        .addGap(18, 18, 18)
                        .addComponent(vendiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(esperienza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numeroInfluenze)
                                    .addComponent(numeroCovid)
                                    .addComponent(numeroEbola)
                                    .addComponent(numeroAngele, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eroiTotali, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(armateTotali)))
                            .addComponent(consegnaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(errore, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(numeroInfluenze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(numeroCovid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(numeroEbola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(armateTotali, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(eroiTotali))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numeroAngele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compraEsperienza)
                    .addComponent(vendiButton))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(esperienza)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addComponent(consegnaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errore, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void compraEsperienzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraEsperienzaActionPerformed
        // TODO add your handling code here:
         if(this.numeroEsperienza<10){
            this.numeroEsperienza++;
            this.esperienza.setText(this.numeroEsperienza+"");
            this.numeroEroiTotali = this.numeroEsperienza < 3 ? 2 : (this.numeroEsperienza<7 ? 1 : 0);
            this.eroiTotali.setText(this.numeroEroiTotali+"");
            this.numeroArmateTotali = 11-this.numeroEsperienza;
            this.armateTotali.setText(this.numeroArmateTotali+"");
        }
    }//GEN-LAST:event_compraEsperienzaActionPerformed

    private void consegnaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consegnaButtonActionPerformed
        // TODO add your handling code here:
        try{
            int influenzaInseriti = Integer.parseUnsignedInt(numeroInfluenze.getText());
            int covidInseriti = Integer.parseUnsignedInt(numeroCovid.getText());
            int ebolaInseriti = Integer.parseUnsignedInt(numeroEbola.getText());
            int angelaDaMondelloInseriti = Integer.parseUnsignedInt(numeroAngele.getText());
            if(influenzaInseriti+covidInseriti+ebolaInseriti+angelaDaMondelloInseriti <= this.numeroArmateTotali){
                this.setVisible(false);
                this.forzaTotale = calcolaForza(influenzaInseriti, covidInseriti, ebolaInseriti, angelaDaMondelloInseriti, numeroEroiTotali);
                this.form.setVisible(true);
            } else {
                errore.setText("Le tue armate superano il numero consentito");
                return;
            }
        } catch (Exception e){
            errore.setText("Devi inserire solo dei numeri positivi");
            return;
        }
       
    }//GEN-LAST:event_consegnaButtonActionPerformed

    private void vendiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendiButtonActionPerformed
        // TODO add your handling code here:
         if(this.numeroEsperienza>1){
            this.numeroEsperienza--;
            this.esperienza.setText(this.numeroEsperienza+"");
            this.numeroEroiTotali = this.numeroEsperienza < 3 ? 2 : (this.numeroEsperienza<7 ? 1 : 0);
            this.eroiTotali.setText(this.numeroEroiTotali+"");
            this.numeroArmateTotali = 11-this.numeroEsperienza;
            this.armateTotali.setText(this.numeroArmateTotali+"");
        }
    }//GEN-LAST:event_vendiButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel armateTotali;
    private javax.swing.JButton compraEsperienza;
    private javax.swing.JButton consegnaButton;
    private javax.swing.JLabel eroiTotali;
    private javax.swing.JLabel errore;
    private javax.swing.JLabel esperienza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField numeroAngele;
    private javax.swing.JTextField numeroCovid;
    private javax.swing.JTextField numeroEbola;
    private javax.swing.JTextField numeroInfluenze;
    private javax.swing.JButton vendiButton;
    // End of variables declaration//GEN-END:variables
}
